apiVersion: v1
data:
  admin.password: JDJhJDEwJFhDaFlIMWgvZ0YxVUVkemFwVXpRME92Z21kOG03c04wdXVsRjIuT0tpUWV5ZW4yWU9Wb2dH
  admin.passwordMtime: MjAyNS0wNi0wNlQxMzoyMjo0M1o=
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: argocd
    app.kubernetes.io/name: argocd-secret
    app.kubernetes.io/part-of: argocd
  name: argocd-secret
  namespace: argocd
type: Opaque
