apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kong-controller-validation-webhook-cert
  namespace: kong
spec:
  commonName: kong-controller-validation-webhook.kong.svc
  dnsNames:
    - kong-controller-validation-webhook.kong.svc.cluster.local
    - kong-controller-validation-webhook.kong.svc
    - kong-controller-validation-webhook
  duration: 4380h
  issuerRef:
    kind: Issuer
    name: kong-ca-issuer
  renewBefore: 720h
  secretName: kong-controller-validation-webhook
  usages:
    - digital signature
    - key encipherment
    - server auth
