apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: kong-ca-certificate
  namespace: kong
spec:
  commonName: foMM K8S Kong CA
  duration: 43800h
  isCA: true
  issuerRef:
    kind: ClusterIssuer
    name: lab-k8s-ca-issuer
  renewBefore: 1440h
  secretName: kong-ca-secret
  usages:
    - digital signature
    - key encipherment
    - cert sign
