apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-upgrade,pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
  labels:
    app.kubernetes.io/instance: kuma
    app.kubernetes.io/name: kuma
  name: kuma-install-crds
  namespace: kuma-system
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kuma
        app.kubernetes.io/name: kuma
      name: kuma-install-crds-job
    spec:
      containers:
        - command:
            - /kuma/scripts/install_crds.sh
          image: docker.io/bitnami/kubectl:1.32.2
          name: pre-upgrade-job
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 65534
          volumeMounts:
            - mountPath: /kuma/crds
              name: crds
              readOnly: true
            - mountPath: /kuma/scripts
              name: scripts
              readOnly: true
      initContainers:
        - args:
            - /kuma/scripts/save_crds.sh
          command:
            - sh
            - -c
          image: docker.io/kumahq/kumactl:2.10.1
          name: pre-upgrade-job-init
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext:
            readOnlyRootFilesystem: true
          volumeMounts:
            - mountPath: /kuma/crds
              name: crds
            - mountPath: /kuma/scripts
              name: scripts
              readOnly: true
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
      serviceAccountName: kuma-install-crds
      volumes:
        - configMap:
            defaultMode: 493
            name: kuma-install-crds-scripts
          name: scripts
        - emptyDir: {}
          name: crds
