apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    helm.sh/hook-weight: "5"
  labels:
    app.kubernetes.io/instance: kuma
    app.kubernetes.io/name: kuma
  name: kuma-patch-ns
  namespace: kuma-system
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: kuma
        app.kubernetes.io/name: kuma
      name: kuma-patch-ns-script
    spec:
      containers:
        - command:
            - kubectl
            - patch
            - namespace
            - kuma-system
            - --type
            - merge
            - --patch
            - '{ "metadata": { "labels": { "kuma.io/system-namespace": "true" } } }'
          image: docker.io/bitnami/kubectl:1.32.2
          name: pre-install-job
          resources:
            limits:
              cpu: 100m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 256Mi
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 65534
      nodeSelector:
        kubernetes.io/os: linux
      restartPolicy: OnFailure
      securityContext:
        runAsNonRoot: true
      serviceAccountName: kuma-patch-ns-job
