apiVersion: v1
kind: Service
metadata:
  labels:
    app: kuma-egress
    app.kubernetes.io/instance: kuma
    app.kubernetes.io/name: kuma
  name: kuma-egress
  namespace: kuma-system
spec:
  ports:
    - port: 10002
      protocol: TCP
      targetPort: 10002
  selector:
    app: kuma-egress
    app.kubernetes.io/instance: kuma
    app.kubernetes.io/name: kuma
  type: ClusterIP
