apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "5680"
    prometheus.io/scrape: "true"
  labels:
    app: kuma-control-plane
    app.kubernetes.io/instance: kuma
    app.kubernetes.io/name: kuma
  name: kuma-control-plane
  namespace: kuma-system
spec:
  ports:
    - appProtocol: http
      name: diagnostics
      port: 5680
    - appProtocol: http
      name: http-api-server
      port: 5681
    - appProtocol: https
      name: https-api-server
      port: 5682
    - appProtocol: https
      name: https-admission-server
      port: 443
      targetPort: 5443
    - appProtocol: https
      name: mads-server
      port: 5676
    - appProtocol: https
      name: dp-server
      port: 5678
  selector:
    app: kuma-control-plane
    app.kubernetes.io/instance: kuma
    app.kubernetes.io/name: kuma
  type: ClusterIP
