apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: kuma-control-plane
    app.kubernetes.io/instance: kuma
    app.kubernetes.io/name: kuma
  name: kuma-control-plane
  namespace: kuma-system
