apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
    app: kuma-control-plane
    app.kubernetes.io/instance: kuma
    app.kubernetes.io/name: kuma
  name: kuma-validating-webhook-configuration
  namespace: kuma-system
webhooks:
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lRSGdwOEs3MTBaQW5JZ2tuaDBDeVMwakFOQmdrcWhraUc5dzBCQVFzRkFEQVMKTVJBd0RnWURWUVFERXdkcmRXMWhMV05oTUI0WERUSTFNRFl3TnpBMk5UVXlNVm9YRFRNMU1EWXdOVEEyTlRVeQpNVm93RWpFUU1BNEdBMVVFQXhNSGEzVnRZUzFqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU54NlZmVHJLc2R1YlkzRjRUSlhiVW1EK05MZzl1MmJZdzdubkE1UUtYVlovNmc1TGg2WDhhY3kKK040Qm5sTVRHRTBUa2lKUWRYRWdzbTluQi9HYTRtVTdsTnVDOG44clc3elFML3RXL3RydHJEaTlCNDVlaE9CdwptRFA2SERIQUdqRjNVQmtNV3p4N0x6U2xjSmhqNzRtdVltemlYYTFMb1RhT1BVNVA2S2t2RnU1OGtLdXJ0TzJlCml5Tnc5LzZLdHg0N29EakI0Zk5qK2JGTmlIa25kNnJKZVVYclhvMWUxZ2s3bGZ0Y1gwaGZlazNMNzlPdkJFRi8KKzdYZUxDQy9MVWN0MTh5TmZyNzNZbldaNnhYdG9MTGU0M3YyUUVKVGxaVHAwU1h0UDN2VkE1cFJ1ZGkwa2ZnWAozeFJTdlFibkdBSzg3VGNpUjdBNzNEc2p5TWRGTnUwQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trCk1CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBREFRSC8KTUIwR0ExVWREZ1FXQkJTcktuMjg4QUFtM0svandYS3NER2EzbHlzT1B6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBaHZvRWlMN3gyT1MycmwvSWpnMjJ0N3A1dStyVjhObHpWeDFXb0RzZUxVM2t5dEUza1E4OTkxeG1VOHVRCm8xNk9KWTVQNGRRNTVjQnY1bDYvaERYWFJTNEhaTzdyUWQyYjArUFdBTTVBQ0JBekQ0ak1YUVVsRThWV2NCNisKR3Mxd0lNamY1bHovLytzaHhtYy9BakgyRmt6TUFOc2kveUt0UzJRMXA4aDd6aG16Uis4Tng1MkZpN05ZbkNYZQpyYUs0V29MNlAxRjdCcTM4OG56K1QzTERDVlF2eWx3dHA5ME9HNFQrZ2Z3OTMvWCtUU2VjSkVVWm5pcjR2RElOCkgxN2N0L1U1SHNTdVZnd0I0T0RzQkN4SjQvSkU0K1NZaDNjc2ExV2hWaGdhN09jR0RiWWN2ZjRBc3pWNXlnVWEKTk5DTDZPWkFBWlZQYmYweGczK3pQckc3S0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: kuma-control-plane
        namespace: kuma-system
        path: /validate-kuma-io-v1alpha1
    failurePolicy: Fail
    name: validator.kuma-admission.kuma.io
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: NotIn
          values:
            - kube-system
    rules:
      - apiGroups:
          - kuma.io
        apiVersions:
          - v1alpha1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - circuitbreakers
          - dataplanes
          - externalservices
          - faultinjections
          - meshgatewayinstances
          - healthchecks
          - meshes
          - meshgateways
          - meshgatewayroutes
          - proxytemplates
          - ratelimits
          - retries
          - trafficlogs
          - trafficpermissions
          - trafficroutes
          - traffictraces
          - virtualoutbounds
          - zones
          - containerpatches
          - meshaccesslogs
          - meshcircuitbreakers
          - meshfaultinjections
          - meshhealthchecks
          - meshhttproutes
          - meshloadbalancingstrategies
          - meshmetrics
          - meshpassthroughs
          - meshproxypatches
          - meshratelimits
          - meshretries
          - meshtcproutes
          - meshtimeouts
          - meshtlses
          - meshtraces
          - meshtrafficpermissions
          - hostnamegenerators
          - meshexternalservices
          - meshmultizoneservices
          - meshservices
    sideEffects: None
  - admissionReviewVersions:
      - v1
    clientConfig:
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUREekNDQWZlZ0F3SUJBZ0lRSGdwOEs3MTBaQW5JZ2tuaDBDeVMwakFOQmdrcWhraUc5dzBCQVFzRkFEQVMKTVJBd0RnWURWUVFERXdkcmRXMWhMV05oTUI0WERUSTFNRFl3TnpBMk5UVXlNVm9YRFRNMU1EWXdOVEEyTlRVeQpNVm93RWpFUU1BNEdBMVVFQXhNSGEzVnRZUzFqWVRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQU54NlZmVHJLc2R1YlkzRjRUSlhiVW1EK05MZzl1MmJZdzdubkE1UUtYVlovNmc1TGg2WDhhY3kKK040Qm5sTVRHRTBUa2lKUWRYRWdzbTluQi9HYTRtVTdsTnVDOG44clc3elFML3RXL3RydHJEaTlCNDVlaE9CdwptRFA2SERIQUdqRjNVQmtNV3p4N0x6U2xjSmhqNzRtdVltemlYYTFMb1RhT1BVNVA2S2t2RnU1OGtLdXJ0TzJlCml5Tnc5LzZLdHg0N29EakI0Zk5qK2JGTmlIa25kNnJKZVVYclhvMWUxZ2s3bGZ0Y1gwaGZlazNMNzlPdkJFRi8KKzdYZUxDQy9MVWN0MTh5TmZyNzNZbldaNnhYdG9MTGU0M3YyUUVKVGxaVHAwU1h0UDN2VkE1cFJ1ZGkwa2ZnWAozeFJTdlFibkdBSzg3VGNpUjdBNzNEc2p5TWRGTnUwQ0F3RUFBYU5oTUY4d0RnWURWUjBQQVFIL0JBUURBZ0trCk1CMEdBMVVkSlFRV01CUUdDQ3NHQVFVRkJ3TUJCZ2dyQmdFRkJRY0RBakFQQmdOVkhSTUJBZjhFQlRBREFRSC8KTUIwR0ExVWREZ1FXQkJTcktuMjg4QUFtM0svandYS3NER2EzbHlzT1B6QU5CZ2txaGtpRzl3MEJBUXNGQUFPQwpBUUVBaHZvRWlMN3gyT1MycmwvSWpnMjJ0N3A1dStyVjhObHpWeDFXb0RzZUxVM2t5dEUza1E4OTkxeG1VOHVRCm8xNk9KWTVQNGRRNTVjQnY1bDYvaERYWFJTNEhaTzdyUWQyYjArUFdBTTVBQ0JBekQ0ak1YUVVsRThWV2NCNisKR3Mxd0lNamY1bHovLytzaHhtYy9BakgyRmt6TUFOc2kveUt0UzJRMXA4aDd6aG16Uis4Tng1MkZpN05ZbkNYZQpyYUs0V29MNlAxRjdCcTM4OG56K1QzTERDVlF2eWx3dHA5ME9HNFQrZ2Z3OTMvWCtUU2VjSkVVWm5pcjR2RElOCkgxN2N0L1U1SHNTdVZnd0I0T0RzQkN4SjQvSkU0K1NZaDNjc2ExV2hWaGdhN09jR0RiWWN2ZjRBc3pWNXlnVWEKTk5DTDZPWkFBWlZQYmYweGczK3pQckc3S0E9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: kuma-control-plane
        namespace: kuma-system
        path: /validate-v1-secret
    failurePolicy: Ignore
    name: secret.validator.kuma-admission.kuma.io
    namespaceSelector:
      matchLabels:
        kuma.io/system-namespace: "true"
    rules:
      - apiGroups:
          - ""
        apiVersions:
          - v1
        operations:
          - CREATE
          - UPDATE
          - DELETE
        resources:
          - secrets
    sideEffects: None
