apiVersion: isindir.github.com/v1alpha3
kind: SopsSecret
metadata:
    name: argocd-secrets-sops
    namespace: argocd
spec:
    suspend: false
    secretTemplates:
        - name: argocd-repo
          type: Opaque
          labels:
            argocd.argoproj.io/secret-type: repository
          stringData:
            sshPrivateKey: ENC[AES256_GCM,data:rVbKPWCefm+lBwndWDgkCDLtOYQdtsbx+Ox3Zx4th4axx9i3X4E6Z15dU4r3A8bPYb5VG7btWG8JIYP+B1YHfyOCpSgEzsAnqwR32vsNPPCi7b9GRKtWbhcSmJSXPCfxdbX0QwXZp8tmICB7ixHHkV779ThUhSFXVGpZq0+HnVCHqi1K1obP6UZeebhubArjA1sIwgyvzrOpNhk2CLimrIYf1puKjMvztMpKAJp+ytMhMhgWzsyToZqdbQFp3M5QBV/vcrsDMMJZ/GrPwWLqKaz8L2nQhjIrt4Oicma5iBm3NQuvFDAzzQIn1rvwLaYJvb7Ursx8IbPdGU/5JvsMKltmMrdnM+XO5xaFevFETt/mQiHVJgQ7dceHBG8Ddmu/MKH3pRPuZe5Czj0yE1bzg5Mj4kB0RtihMccGryKjRIuPFEx9AquYna+UxPVCphkaoDCs6I0kc/n3YoAXQN75KdVuqL/YpGl+ROuTX7vQvfmMNomUpafqR9QxXGTo3WoR/PPB,iv:EkqswnbJg1qdcbzOI7NfEe6wm0D4I2ROIMpUiY73kh4=,tag:VBGlzqm2qQoAgiZOZN013g==,type:str]
            type: ENC[AES256_GCM,data:yQlW,iv:qIK8I9rXlRosXRYN3glRN0GR5Ab4bcXZcYHKXKfgGpg=,tag:SoHqwPfb3LW+uZMtV0dqPA==,type:str]
            url: ENC[AES256_GCM,data:R+vh84TaMI92E5vlaaXr6Gt9DGJrkJ0oOOXdOhCUOvpKpWCYSSLD,iv:wmUNC8sEkFVL+9K1Tb+SGB957WTuSQ0xuPcfwPkI6JQ=,tag:umXwrYgQoqnH+oyO6gpr1g==,type:str]
sops:
    hc_vault:
        - vault_address: https://vault.li.lab:8200
          engine_path: sops
          key_name: default
          created_at: "2025-06-06T13:27:14Z"
          enc: vault:v3:0nr0DAvse4ylhjDu8smBlhc/4221b35vjAViKgnG20JPA0L0cxGc8O3yB6J5h8UG6FLqunZUBG2C9Ynq
    age:
        - recipient: age1k7ny39wqnp3qzv46cyxzuj8tghrgflt9mrhd4ly066vz2mksr54q07q9u7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMGVzQURLWFZOWUxJZkFi
            Zm1FOGRMbzlUZmJkZHNXM3dDaHllc1paTEZFCjNVV2liYjFqQy82RzdIT0Flb0tN
            Qk5rVVliTUR5amZVM0NvTWcwaXdVTDAKLS0tIFZ6TytDZnhGdWM2QVJreUY5WG5y
            VEVVYVZPSkhzSUNldjVrbEkvT2ZZK3cKUNFXESU9fC1tbX6FjvVWa8jBT5foEp8L
            KRd2Ypw7ZacXS2GpQFw9Crw1ATlaH/iyJRBjQgrf9xh989WljRlM2w==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age145uvzwjzua4kl0c89dmat00pgz3srfmf4wfzzalnszk5ae6t043ss8x4jj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBId2ZpYXBsU0VjVTh6QitV
            V0JvZHlCcnFxamFCUlovZExCU2hWd2VEbmxNCnNvMGY1RGdRMGFUTnVMV2ZXZU9S
            Umw0SGpjS2hFeHM1NkQvUUl1VjhjREEKLS0tIGowem5ZRVZ2V0ZRMWZNVHdUVlFW
            dXc5eUhoMEtzSVJYZUJNclIwYlNvVXcKAopHcUnQQ0eW0M/aR3jw53Lzuq7ccxVh
            PcyTdrRAkXe6PBxZysr+bdIDCaJ2kmryzhP3FaJXrq0fOysXQlcqKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-06-06T13:27:14Z"
    mac: ENC[AES256_GCM,data:N1dgQeY9BDB4klCwujxSaCKSd30LVhcVESFDUjhmL4/yN/Jf6kvq2UX99gQsNAKK+JSb8wuv0VxU1+Y3qlGoPLOK+gXoN3s9W8Oqpy+z3soxeT6lm7Jj/+N1QBJxchYfFBq1tinjNdUZ87HujWw5D8BFacJpqzAwrFzWtPKccQg=,iv:hNPFPo5ldEA+tpb4K/d6NQPWrU+e42TAidmT6K9sHFE=,tag:b/sO3kwonYFVUfBZOxanWQ==,type:str]
    encrypted_regex: ^(stringData)$
    version: 3.10.2
