apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kuma
  namespace: argocd
spec:
  destination:
    namespace: kuma-system
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/infra/kuma
    repoURL: git@github.com:aufomm/nixidy-argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
