apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sops-secrets-operator
  namespace: argocd
spec:
  destination:
    namespace: sops-operator
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ./manifests/infra/sops-secrets-operator
    repoURL: git@github.com:aufomm/nixidy-argocd.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
