apiVersion: kuma.io/v1alpha1
kind: MeshTrafficPermission
metadata:
  namespace: kuma-system
  name: allow-kong-to-httpbin
  labels:
    kuma.io/mesh: demo
    kuma.io/origin: zone
spec:
  targetRef:
    kind: MeshSubset
    tags:
      kuma.io/service: httpbin-svc_httpbin_svc_80
  from:
  - targetRef:
      kind: MeshSubset
      tags:
        kuma.io/service: kong-gateway-admin_kong_svc_8001
    default:
      action: Allow